apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.appName}}
  labels: 
    app: {{ .Values.appName}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName}}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName}}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if .Values.forceMigError }}
      tolerations:
      - effect: NoExecute
        key: CriticalAddonsOnly
        operator: Equal
        value: "gpusUnavailable"
{{- end }}
      terminationGracePeriodSeconds: 5
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.appName}}
        resources:
          limits:
            {{ .Values.gpuType  }}: {{ .Values.numGPUs  }}
        command:
        - "python"
        - "/workspace/examples/upstream/mnist/main.py"
