apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      volumes:
        - name: {{ .Values.mountPathName }}
          hostPath:
            path: {{ .Values.hostPath }}
            type: {{ .Values.hostPathType }}
      containers:
      - name: {{ .Values.appName }}
        image: k8s.gcr.io/nginx
        volumeMounts:
          - name: {{ .Values.mountPathName }}
            mountPath: {{ .Values.mountPath }}

